[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_src_filter = +<main.cpp>
lib_deps =
  adafruit/Adafruit ILI9341@^1.5.2
  adafruit/Adafruit GFX Library@^1.11.3
  bogde/HX711@^0.7.5
  adafruit/RTClib@^1.13.0
build_flags =
  -D DEFAULT_SPI_FREQUENCY=80000000L
  -D FASTLED_ESP32_I2S_LOCK=1

[env:esp32dev_ads1220]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_src_filter = +<debug/ads1220_debug.cpp>
lib_deps =
  adafruit/Adafruit ILI9341@^1.5.2
  adafruit/Adafruit GFX Library@^1.11.3
  wollewald/ADS1220_WE@^1.0.25
  bogde/HX711@^0.7.5
  adafruit/RTClib@^1.13.0
build_flags =
  -D DEFAULT_SPI_FREQUENCY=80000000L
  -D FASTLED_ESP32_I2S_LOCK=1

[platformio]
default_envs = esp32dev
